import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { parse, print } from 'graphql'
import { EXAMPLES } from './examples.ts'
import {
  LIVE_ENDPOINT,
  LOCAL_ENDPOINT,
  linkFor,
  renderExampleTable,
} from './exampleLinks.ts'

/**
 * The same arrangement `sdl.test.ts` uses for the schema, for the same reason.
 * The README's table is generated by `pnpm examples`; this is what stops the
 * committed block becoming a lie about what the service will actually run.
 */
const readme = readFileSync(new URL('../../README.md', import.meta.url), 'utf8')

describe('the README table of runnable examples', () => {
  it('matches what the examples currently are', () => {
    expect(readme).toContain(renderExampleTable())
  })

  it('links a query that decodes back to the example it claims to be', () => {
    // A link is only worth having if pressing it runs the row you pressed. A
    // table generated from one list and links pasted from another is the whole
    // failure this is written to prevent.
    for (const example of EXAMPLES) {
      const decoded = new URL(linkFor(LIVE_ENDPOINT, example.query)).searchParams.get('query')

      expect(decoded, example.name).toBe(example.query)
      expect(print(parse(decoded ?? '')), example.name).toContain(example.name)
    }
  })

  it('offers both audiences the same list, differing only in host', () => {
    // Local is the onboarding developer, live is the manual tester. If the two
    // columns can drift apart, one of them is testing a different service.
    const table = renderExampleTable()

    expect(table.split(LOCAL_ENDPOINT)).toHaveLength(EXAMPLES.length + 1)
    expect(table.split(LIVE_ENDPOINT)).toHaveLength(EXAMPLES.length + 1)
  })

  it('keeps every link inside a length browsers and markdown handle', () => {
    // Deep links carry the whole query, comments included. 2,000 characters is
    // the conservative ceiling every browser clears; naming it here means a
    // future example that blows past it fails rather than half-loading.
    for (const example of EXAMPLES) {
      expect(linkFor(LIVE_ENDPOINT, example.query).length, example.name).toBeLessThan(2_000)
    }
  })
})
